version: '3.9'
services:
  database:
    image: mongo:7.0.4
    volumes:
      - ./data:/data/db
    restart: always
    ports:
      - 27017:27017
    command: ['--replSet', 'dbrs', '--bind_ip_all']
