name: build and push image
on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+*'
    branches:
      - 'release/v[0-9]+.[0-9]+.[0-9]+*'
      - 'refs/tags/v[0-9]+.[0-9]+.[0-9]+*'

jobs:
  build-image:
    runs-on: ubuntu-latest
    steps:
      - name: Pre-check step and set env prod from release
        if: startsWith(github.ref, 'refs/tags/v')
        id: get_current_env_prod
        run: |
          if [[ ${{ github.event.ref }} =~ ^refs/tags/v[0-9]+\.[0-9]+\.[0-9]+.*$ ]] && [[ ${{ github.event.base_ref }} =~ ^refs/heads/master ]]; then
            echo "VERSION=${GITHUB_REF#refs/tags/}" >> "$GITHUB_ENV"
            echo "[INFO] PASSED pre-check. Using build automatically production from release"
            exit 0
          fi

      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_ACCESS_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/mongo-streamer:latest,${{ secrets.DOCKERHUB_USERNAME }}/mongo-streamer:${{ env.VERSION }}
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache

      - name: Verify
        run: echo ${{ steps.docker_build.outputs.digest }}
